changelog:
  exclude:
    labels:
      - ignore-for-release
      - skip-changelog
      - dependencies
    authors:
      - dependabot
      - dependabot[bot]
  categories:
    - title: 🚀 Features
      labels:
        - feature
        - enhancement
    - title: 🐛 Bug Fixes
      labels:
        - bug
        - bugfix
        - fix
    - title: 🔧 Maintenance
      labels:
        - chore
        - maintenance
        - refactor
    - title: 📚 Documentation
      labels:
        - documentation
        - docs
    - title: 🧪 Testing
      labels:
        - test
        - testing
    - title: 🎨 UI/UX Improvements
      labels:
        - ui
        - ux
        - design
    - title: ⚡ Performance
      labels:
        - performance
        - optimization
    - title: 🔒 Security
      labels:
        - security
    - title: Other Changes
      labels:
        - "*"